# Generated by Django 2.2.24 on 2022-07-15 09:08

from django.db import migrations


def define_building_type(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        flat.new_building = (flat.construction_year >= 2015)
        flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_flat_new_building'),
    ]

    operations = [
        migrations.RunPython(define_building_type)
    ]
