# Generated by Django 2.2.24 on 2022-07-18 09:09

from django.db import migrations


def add_flat_to_owners(apps, scheme_editor):
    Owner = apps.get_model('property', 'Owner')
    Flat = apps.get_model('property', 'Owner')
    for flat in Flat.objects.all():
        flat_owner = Owner.objects.get(name=flat.name)
        flat_owner.add(flat)
        flat_owner.save()

def clean_flats_in_owners(apps, scheme_editor):
    Owner = apps.get_model('property', 'Owner')
    Flat = apps.get_model('property', 'Owner')
    for flat in Flat.objects.all():
        flat_owner = Owner.objects.get(name=flat.name)
        flat_owner.flat = None


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_auto_20220718_1057'),
    ]

    operations = [
        migrations.RunPython(add_flat_to_owners, )
    ]
