# Generated by Django 2.2.24 on 2022-07-28 09:28

from django.db import migrations


def replace_null(apps, schema_editor):
    Complaint = apps.get_model('property', 'Complaint')
    for complaint in Complaint.objects.all():
        if complaint.text is None:
            complaint.text = ''
        complaint.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0016_auto_20220728_1215'),
    ]

    operations = [
        migrations.RunPython(replace_null)
    ]
